#!/bin/sh
# Modified from https://github.com/DanaDanger/victorious-merge

# On merge actions (e.g. merge/pull)
echo "huuuh $GIT_REFLOG_ACTION"
if [ "$GIT_REFLOG_ACTION" != "pull" ]; then
  # If we fought against merge conflicts, play fanfare
  # log="$(git log -n 1 2> /dev/null)"
  echo "wat $log"
  # if echo "$log" | grep "Conflicts:" &> /dev/null; then
    afplay -v 5 "$PWD/.git/hooks/FinalFantasyVictory.mp3" &
  # fi
fi
